# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\UtilisateurAdmin: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\UtilisateurAdmin
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: app_login
                username_path: email
                password_path: password
            
            logout:
                path: app_logout
    
    access_control:
        - { path: ^/api/admin, roles: ROLE_ADMIN }